### ISSUE TITLE
Cover4(裏表紙)を偶数ページに表示したい

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/ah-dita#2]
pdf5-mlとah-ditaをインストールし、裏表紙を出力できるようになりました。
ただ、裏表紙が奇数ページに表示される場合には、余白ページを手作業で入れる手間が必要のようです。
たとえば、sample_cover\pdf5_manual_cover.ditamapで、<chapter href="topics-en/c_Chapter2.dita"･･･>の行をコメントにすると、pdf5_manual_cover.pdfの裏表紙が3ページ目になりました。
裏表紙を紙面の裏（偶数ページ）に常に表示する制御機能が搭載されていたら、指定方法を教えていただけると助かります。

**Comment by ToshihikoMakita** [comment]
すみません．今週出張で超忙しいので、週末に調べます．
少しお時間をください．

**Comment by ToshihikoMakita** [comment]
[https://github.com/AntennaHouse/pdf5-ml/blob/master/com.antennahouse.pdf5.ml/xsl/dita2fo_cover_print.xsl](dita2fo_cover_print.xsl) をご覧ください．

    <topicref href="cover3.dita" outputclass="cover3" navtitle="表３"/>
    <topicref href="cover4.dita" outputclass="cover4" navtitle="表４"/>

のように記述すると、cover3.ditaを自動的に奇数ページ始まりとするコードが入っています．

        <xsl:if test="$pIsPrintOutput and ahf:isCover3TopicRef($prmTopicRef)">
            
            <xsl:attribute name="initial-page-number" select="'auto-odd'"/>
        </xsl:if>

表１～表３は強制的にすべて１ページとしていますので、表３が奇数ページならば、表4は偶数ページになってくれるはずです．上記のようなマップを作っていただき、一度お試しいただけるでしょうか？

**Comment by tmaeda3** [comment]
解決しました。output.typeをwebに設定していたのも一因でした。ありがとうございました。
