### ISSUE TITLE
Three missing entries in catalog and one wrong public ID

### ISSUE THREAD

**Issue by AndeeZee** [AntennaHouse/ah-dita#5]
Hello!

Depending on which software you're using to parse the documents, you might get some parsing issues, which can be fixed as follows:

1) plugins\com.antennahouse.dita.dita13.doctypes\doctypes\dtd\bookmap\catalog.dtd
missing
```
<public publicId="-//ANTENNA HOUSE//ELEMENTS DITA BookMap//EN" uri="dtd/bookmap.mod"/>
<public publicId="-//ANTENNA HOUSE//ELEMENTS DITA 1.x BookMap//EN" uri="dtd/bookmap.mod"/>
<public publicId="-//ANTENNA HOUSE//ELEMENTS DITA 1.3 BookMap//EN" uri="dtd/bookmap.mod"/>
```

2) plugins\com.antennahouse.dita.dita13.doctypes\doctypes\dtd\technicalContent\dtd\reference.dtd
Line **52**
```
<!ENTITY % glossentry-dec
  PUBLIC "-//OASIS//ENTITIES DITA 1.3 Glossary Entry//EN"
         "../../../../../org.oasis-open.dita.v1_3/dtd/technicalContent/dtd/glossentry.ent"
>%glossentry-dec;
```
**OASIS** instead of **ANTENNA HOUSE**, because it uses the default ones.

Would you be so kind to have a look into this?

Thank you,
Andy

**Comment by ToshihikoMakita** [comment]
@AndeeZee
Thank you for your indication.

> Depending on which software you're using to parse the documents

What software do you using and how to find this bug?

**Comment by AndeeZee** [comment]
Hello!
I was uploading the plugin to the IXIASOFT CCMS, which has very good and strict parsing capabilitites. And it didn't accepted the plugin, without these changes.
Kind regards,
Andreas

**Comment by ToshihikoMakita** [comment]
I got it. Thank you for the explanation.
